name: Fork Windows Build Steps - Qt

on:
  workflow_call:
    inputs:
      jobName:
        required: true
        type: string
      os:
        required: false
        type: string
        default: windows-2022
      platform:
        required: false
        type: string
        default: x64
      configuration:
        required: true
        type: string
      simd:
        required: false
        type: string
        default: AVX2
      buildSystem:
        required: false
        type: string
        default: msbuild
      cmakeFlags:
        required: false
        type: string
        default: ""
      qt_binary_url:
        required: false
        type: string
        default: https://github.com/PCSX2/pcsx2-windows-dependencies/releases/download/2022-11-20/qt-6.4.0-x64.7z
      qt_dir:
        required: false
        type: string
        default: 3rdparty\qt\6.4.0\msvc2022_64
      cheats_url:
        required: false
        type: string
        default: https://github.com/PCSX2/pcsx2_patches/releases/latest/download

jobs:
  build_windows_qt:
    name: ${{ inputs.jobName }}
    runs-on: ${{ inputs.os }}
    # Set some sort of timeout in the event of run-away builds.  We are limited on concurrent jobs so, get rid of them.
    timeout-minutes: 60
    env:
      POWERSHELL_TELEMETRY_OPTOUT: 1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Prepare Artifact Metadata
        id: artifact-metadata
        shell: bash
        env:
          OS: windows
          BUILD_SYSTEM: ${{ inputs.buildSystem }}
          GUI_FRAMEWORK: Qt
          ARCH: ${{ inputs.platform }}
          SIMD: ${{ inputs.simd }}
          EVENT_NAME: ${{ github.event_name }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_NUM: ${{ github.event.pull_request.number }}
          PR_SHA: ${{ github.event.pull_request.head.sha }}
        run: ./.github/workflows/scripts/common/name-artifacts-fork.sh

      - name: Setup msbuild
        if: inputs.configuration != 'CMake'
        uses: microsoft/setup-msbuild@v1

      - name: Download Qt build files
        shell: cmd
        run: |
          cd 3rdparty\qt
          aria2c ${{ inputs.qt_binary_url }}
          7z x qt-*-x64.7z
          del qt-*-x64.7z

      - name: Download cheats
        shell: cmd
        run: |
          cd bin/resources
          aria2c -Z "${{ inputs.cheats_url }}/cheats_ni.zip" "${{ inputs.cheats_url }}/cheats_ws.zip"

      - name: Generate CMake
        if: inputs.configuration == 'CMake'
        id: cmake
        shell: cmd
        run: |
          call "%ProgramFiles%\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cmake . -B build "-DCMAKE_PREFIX_PATH=%cd%\${{ inputs.qt_dir }}" -DQT_BUILD=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON -G Ninja

      - name: Build PCSX2
        shell: cmd
        run: |
          if "${{ inputs.configuration }}"=="CMake" (
            call "%ProgramFiles%\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
            cmake --build build --config Release || exit /b
            cmake --install build --config Release || exit /b
          ) else (
            msbuild "PCSX2_qt.sln" /m /v:m /p:Configuration="${{ inputs.configuration }}" /p:Platform="${{ inputs.platform }}"
          )

      - name: Download Plugin Injector artifact
        uses: robinraju/release-downloader@v1.6
        with:
          repository: "ThirteenAG/PCSX2PluginInjector"
          tag: "latest"
          fileName: "PCSX2PluginInjector.zip"
      - name: Unpack Plugin Injector
        run: |
          7z x PCSX2PluginInjector.zip -obin/ -y
          del PCSX2PluginInjector.zip
      - name: Pack binaries
        uses: ThirteenAG/zip-release@master
        with:
          path: './bin/**'
          type: 'zip'
          filename: PCSX2Fork-Windows-${{ inputs.platform }}-${{ inputs.jobName }}.zip
          exclusions: '*.bsc *.exp *.ilk *.iobj *.ipdb *.pdb *.lib'
      - name: Get release info
        id: release_info
        uses: cardinalby/git-get-release-action@1.2.4
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: latest
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          name: ${{ steps.release_info.outputs.name }}
          body: ${{ steps.release_info.outputs.body }}
          tag: ${{ steps.release_info.outputs.tag_name }}
          artifacts: "*.zip"
