name: Fork Windows Builds

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  # MSBUILD
  lint_vs_proj_files:
    name: Lint VS Project Files
    runs-on: windows-2022
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Verify VS Project Files
        run: .github\workflows\scripts\windows\validate-vs-filters.ps1

  build_qt_sse4:
    needs: lint_vs_proj_files
    name: "SSE4"
    uses: ./.github/workflows/windows_build_qt_fork.yml
    with:
      jobName: Qt
      configuration: Release
      simd: "SSE4"
    secrets: inherit

  build_qt_avx2:
    needs: lint_vs_proj_files
    name: "AVX2"
    uses: ./.github/workflows/windows_build_qt_fork.yml
    with:
      jobName: Qt
      configuration: Release AVX2
    secrets: inherit

  build_qt_sse4_cmake:
    name: "CMake SSE4"
    uses: ./.github/workflows/windows_build_qt_fork.yml
    with:
      jobName: Qt
      configuration: CMake
      buildSystem: cmake
    secrets: inherit
